### PR TITLE
Use screen colours to print results

### PR DESCRIPTION
**Pull request by hlovdal**
Add support for printing good/bad results with red/green colour coding so that it is easy to see the overall results at a quick glance rather than having to read and interpret the text.

### CODE REVIEW

**Comment by mhagger** [comment]
Thanks for the PR. I love the idea of adding color to the output!

…but I'm not psyched about adding a dependency on a non-stdlib package. Note that it would be the first non-stdlib dependency, so it would add a disproportionate amount of complication for people who just want to download and run the script.

Would it be possible to use a lighter-weight solution for adding the color directives, perhaps as simple as [this one here](https://github.com/mhagger/git-imerge/blob/002b8bd9df0f3ce9e09ab142b10da5df4051e715/git-imerge#L146-L183)? Then the `colorama` dependency could be made completely optional:

* Only import it at all on Windows
* Put `try...except` around the import, and only invoke `init()` if the package could be loaded successfully
* Document the optional dependency in the README

Also, please don't import `init` into the file namespace. It would be too easy to confuse with a local function.

Thanks!

**Comment by hlovdal** [comment]
I dropped the colorama library and copied the code from git-imerge, so no dependencies any longer. There is no colour support for Powershell or Cmd windows on Windows 10, but those will just fall back to plain text as before. Cygwin, Git Bash and WSL all has colour support (as well as unix of course).

While looking at the code for git-imerge I also copied the command line options, although I simplified to let colour support be enabled by default.

**Comment by mhagger** [comment]
@hlovdal: Thanks, that's great! :sparkles:

I've pushed a branch `add-colour-support` to my repo with two suggested tweaks on top of your branch:

* ab6fccb966d851dc03d3b59b40221184d50240e3 — respect `--color` and `--no-color` before falling back to heuristics
* bd4507738b71c3921e2651d980b90f63da10e71e — use `AnsiColor.CYAN` (rather than `YELLOW`) for highlighting messages unrelated to the success/failure of the actual tests.

What do you think? If you have no objections, I'll merge your branch plus my tweaks.

Thanks again for your work!

**Comment by hlovdal** [comment]
All good 👍

**Pull request merged**
